/**
 * Kaun Banega College Pati — Mock Question Data
 *
 * All 12 questions verbatim from the master brief §10.
 * This file is the client-side data source used BEFORE the database is wired.
 * Once the DB is connected, questions are loaded from the API, but this file
 * remains as a fallback and reference.
 *
 * DO NOT edit questions here after DB is wired — edit via the admin panel instead.
 */

import { Question } from './types';

export const MOCK_QUESTIONS: Question[] = [
  {
    id: 'q1',
    questionNumber: 1,
    questionText: 'College mein sabse POWERFUL sentence kaunsa hai?',
    optionA: '"Assignment submit kar diya?"',
    optionB: '"Attendance short hai."',
    optionC: '"Principal sir bula rahe hain."',
    optionD: '"Beta, ek minute staffroom mein aana."',
    correctOptions: ['D'],
    fiftyFiftyRemove: ['A', 'B'],
    fiftyFiftyEligible: true,
    timerDuration: 30,
    audiencePollA: 15,
    audiencePollB: 12,
    audiencePollC: 8,
    audiencePollD: 65,
    correctMessage: 'Ye sunte hi students ka Wi-Fi signal bhi chala jaata hai. 📶',
    wrongMessage: null,
    enabled: true,
  },
  {
    id: 'q2',
    questionNumber: 2,
    questionText: 'Faculty ka sabse DANGEROUS superpower kya hai?',
    optionA: '2x speed pe lecture complete karna',
    optionB: 'Backbenchers ko bina dekhe identify kar lena',
    optionC: 'Attendance sheet yaad rakhna',
    optionD: '10 saal purani mistake yaad rakhna',
    correctOptions: ['B'],
    fiftyFiftyRemove: ['A', 'D'],
    fiftyFiftyEligible: true,
    timerDuration: 30,
    // Q2 has real audience poll values from the brief
    audiencePollA: 11,
    audiencePollB: 64,
    audiencePollC: 18,
    audiencePollD: 7,
    correctMessage: 'Ye log CCTV se bhi aage hain. 🗿',
    wrongMessage: null,
    enabled: true,
  },
  {
    id: 'q3',
    questionNumber: 3,
    questionText: 'College mein "5 minutes mein aa raha hoon" ka ACTUAL meaning kya hota hai?',
    optionA: '5 minutes',
    optionB: '10 minutes',
    optionC: '15 minutes',
    optionD: 'Human civilization ke hisaab se — UNKNOWN',
    correctOptions: ['D'],
    fiftyFiftyRemove: ['A', 'B'],
    fiftyFiftyEligible: true,
    timerDuration: 30,
    audiencePollA: 5,
    audiencePollB: 10,
    audiencePollC: 15,
    audiencePollD: 70,
    correctMessage: 'Scientists ispe abhi bhi research kar rahe hain. 🔬',
    wrongMessage: null,
    enabled: true,
  },
  {
    id: 'q4',
    questionNumber: 4,
    questionText: 'Student jab bolta hai "Sir/Ma\'am, ek GENUINE reason hai…" — toh usually kya hone wala hai?',
    optionA: 'Sach bolne wala hai',
    optionB: 'Medical emergency',
    optionC: 'Ek CINEMATIC backstory start hone wali hai',
    optionD: 'NASA ka mission explain karega',
    correctOptions: ['C'],
    fiftyFiftyRemove: ['A', 'B'],
    fiftyFiftyEligible: true,
    timerDuration: 30,
    audiencePollA: 8,
    audiencePollB: 10,
    audiencePollC: 72,
    audiencePollD: 10,
    correctMessage: 'Oscar nomination pending hai is backstory ki. 🎬🏆',
    wrongMessage: null,
    enabled: true,
  },
  {
    id: 'q5',
    questionNumber: 5,
    questionText: 'Faculty ka favourite attendance percentage?',
    optionA: '50%',
    optionB: '65%',
    optionC: '75%',
    optionD: '100% — because dreams are free',
    correctOptions: ['D'],
    fiftyFiftyRemove: ['A', 'B'],
    fiftyFiftyEligible: true,
    timerDuration: 30,
    audiencePollA: 5,
    audiencePollB: 8,
    audiencePollC: 22,
    audiencePollD: 65,
    correctMessage: 'Sapne dekhne ke paise nahi lagte. 😭✨',
    wrongMessage: null,
    enabled: true,
  },
  {
    id: 'q6',
    questionNumber: 6,
    questionText: 'Exam ke EK DIN pehle student ka sabse common dialogue?',
    optionA: '"Preparation complete hai."',
    optionB: '"Bas revision kar raha hoon."',
    optionC: '"Important questions bhej do please 😭"',
    optionD: '"Sir paper tough mat rakhna."',
    correctOptions: ['C'],
    fiftyFiftyRemove: ['A', 'B'],
    fiftyFiftyEligible: true,
    timerDuration: 30,
    audiencePollA: 5,
    audiencePollB: 12,
    audiencePollC: 68,
    audiencePollD: 15,
    correctMessage: 'Ye message group mein exactly 11:58 PM pe aata hai. ⏰',
    wrongMessage: null,
    enabled: true,
  },
  {
    id: 'q7',
    questionNumber: 7,
    questionText: 'Staffroom mein sabse zyada kya milta hai?',
    optionA: 'Chai ☕',
    optionB: 'Attendance discussions',
    optionC: 'Student stories',
    optionD: 'Above all of the above',
    correctOptions: ['D'],
    fiftyFiftyRemove: ['B', 'C'],
    fiftyFiftyEligible: true,
    timerDuration: 30,
    audiencePollA: 20,
    audiencePollB: 5,
    audiencePollC: 10,
    audiencePollD: 65,
    correctMessage: 'Staffroom = college ka unofficial parliament. ☕🏛️',
    wrongMessage: null,
    enabled: true,
  },
  {
    id: 'q8',
    questionNumber: 8,
    questionText: 'Jab teacher bolte hain "This will NOT come in the exam"…',
    optionA: 'It definitely won\'t come',
    optionB: 'It will come for 1 mark',
    optionC: 'It will come for 10 marks',
    optionD: 'Students collectively lose trust in humanity',
    correctOptions: ['D'],
    fiftyFiftyRemove: ['A', 'B'],
    fiftyFiftyEligible: true,
    timerDuration: 30,
    audiencePollA: 3,
    audiencePollB: 10,
    audiencePollC: 15,
    audiencePollD: 72,
    correctMessage: 'Ek sentence. Zindagi bhar ka trust issue. 💔',
    wrongMessage: null,
    enabled: true,
  },
  {
    id: 'q9',
    questionNumber: 9,
    questionText: 'College ka sabse MYSTERIOUS creature kaun hai?',
    optionA: 'Student who submits assignment EARLY',
    optionB: 'Student with 100% attendance',
    optionC: 'Student who actually reads the syllabus',
    optionD: 'All of the above — sightings are extremely rare',
    correctOptions: ['D'],
    fiftyFiftyRemove: ['A', 'B'],
    fiftyFiftyEligible: true,
    timerDuration: 30,
    audiencePollA: 10,
    audiencePollB: 8,
    audiencePollC: 12,
    audiencePollD: 70,
    correctMessage: 'National Geographic bhi shoot nahi kar paaya. 🦕',
    wrongMessage: null,
    enabled: true,
  },
  {
    id: 'q10',
    questionNumber: 10,
    questionText: 'Teacher ke "I\'ll wait" ka ACTUAL meaning?',
    optionA: 'Take your time',
    optionB: 'I am patient',
    optionC: 'You have EXACTLY 3 seconds to fix your life',
    optionD: 'Class dismissed',
    correctOptions: ['C'],
    fiftyFiftyRemove: ['A', 'B'],
    fiftyFiftyEligible: true,
    timerDuration: 60,
    audiencePollA: 5,
    audiencePollB: 8,
    audiencePollC: 75,
    audiencePollD: 12,
    correctMessage: '3 seconds. Timer already start ho chuka hai. ⏳🗿',
    wrongMessage: null,
    enabled: true,
  },
  {
    id: 'q11',
    questionNumber: 11,
    questionText: 'Faculty ko sabse zyada kis cheez ki zarurat hoti hai?',
    optionA: 'Coffee',
    optionB: 'Patience',
    optionC: 'Wi-Fi',
    optionD: 'All three + salary on time 😭',
    correctOptions: ['D'],
    fiftyFiftyRemove: ['A', 'C'],
    fiftyFiftyEligible: true,
    timerDuration: 60,
    audiencePollA: 10,
    audiencePollB: 12,
    audiencePollC: 8,
    audiencePollD: 70,
    correctMessage: 'Faculty bhi insaan hai. Legend insaan, but insaan. 🫡',
    wrongMessage: null,
    enabled: true,
  },
  {
    id: 'q12',
    questionNumber: 12,
    questionText: 'Ek teacher ko truly LEGENDARY kya banata hai?',
    optionA: 'Knowledge',
    optionB: 'Patience',
    optionC: 'Students ko motivate karna',
    optionD: 'Saalon baad bhi students ka unhe yaad rakhna ❤️',
    correctOptions: ['D'],
    fiftyFiftyRemove: ['A', 'B'],
    fiftyFiftyEligible: true,
    timerDuration: 60,
    audiencePollA: 10,
    audiencePollB: 8,
    audiencePollC: 12,
    audiencePollD: 70,
    correctMessage: 'Padhai bhool jaoge… par wo ek class yaad rahegi. ❤️',
    wrongMessage: null,
    enabled: true,
  },
];
